api_hash: 4da03a108492e1d45d18f21eded76cfc
api_id: 26645966
session_name: user_session
# 移除bot_token，使用用户账号

# 代理配置 - 使用本地HTTP代理服务
# proxy:
#   scheme: http
#   hostname: 127.0.0.1
#   port: 7890
#   username: ''
#   password: ''

chat:
- chat_id: dyjs01
  last_read_message_id: 33
  download_filter: media_type == r'(photo|video|document|audio)'
# - chat_id: python
#   last_read_message_id: 1358893
#   download_filter: media_type == r'(photo|video|document|audio)'
# - chat_id: github
#   last_read_message_id: 0
#   download_filter: media_type == r'(photo|video|document|audio)'
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
file_path_prefix:
- chat_id
- media_datetime
media_types:
- audio
- photo
- video
- document
- voice
- video_note
save_path: /home/ec2-user/media
web_host: 0.0.0.0
web_port: 5504
language: ZH
web_login_secret: 123456
max_download_task: 0  # 最大下载任务数通常5, 0: 禁用下载
file_name_prefix:
- message_id
- file_name
file_name_prefix_split: ' - '
hide_file_name: false
allowed_user_ids:
- me
date_format: '%Y_%m'
enable_download_txt: false
