api_hash: 4da03a108492e1d45d18f21eded76cfc
api_id: 26645966
session_name: media_downloader
bot_token: 7768865131:AAHArbvzadeXr4yP8voqiO-IFYe83gif0bA
# 机器人模式：只能下载转发给机器人的消息
chat:
- chat_id: me
  last_read_message_id: 0
  download_filter: 'true'
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
file_path_prefix:
- chat_id
- media_datetime
media_types:
- audio
- photo
- video
- document
- voice
- video_note
save_path: /home/ec2-user/media
web_host: 127.0.0.1
web_port: 8082
language: ZH
web_login_secret: 123456
max_download_task: 5
file_name_prefix:
- message_id
- file_name
file_name_prefix_split: ' - '
hide_file_name: false
allowed_user_ids:
- me
date_format: '%Y_%m'
enable_download_txt: false 